### ISSUE TITLE
When the target resourcegroup is not created by Pulumi, but supplied via configuration, dependency resolution hicks up

### ISSUE THREAD

**Issue by ModernRonin** [pulumi/pulumi-azure-native#1031]
Example:

my stack looks like this:
```typescript
const resourceGroupName= cfg.require("ResourceGroup");

// ...
const redisCache= createRedis();
// ...
function createRedis() : azure.types.input.web.NameValuePairArgs[]{
    var cache= new redis.Redis("redis", {
        resourceGroupName,
        enableNonSslPort: true,
        minimumTlsVersion: redis.TlsVersion.TlsVersion_1_2,
        sku: {
            name: "Basic",
            family: "C",
            capacity: cfg.requireNumber("Redis.Size")
        }
    });
    
    const keys= pulumi.all([resourceGroupName, cache.name])
                 .apply(([resourceGroupName, name])=>redis.listRedisKeys({resourceGroupName, name}));
    const connectionString= pulumi.interpolate `${cache.hostName}:6380,password=${keys.primaryKey},ssl=True,abortConnect=False`;
    return [
        {
            name: "Redis:ConnectionString",
            value: connectionString
        },
    ];
}
```
When I run this on a clean target environment, it fails at preview with an error like:
```
Diagnostics:
  pulumi:pulumi:Stack (Cloud-dev):
    error: Running program 'C:\Projects\Deon\infrastructure\azureresources' failed with an unhandled exception:
    Error: invocation of azure-native:cache:listRedisKeys returned an error: request failed /subscriptions/25110286-d288-4e46-851b-4e2bc880672f/resourceGroups/rgDEV/providers/Microsoft.Cache/redis/redis2f94d61f/listKeys: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Cache/Redis/redis2f94d61f' under resource group 'rgDEV' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
        at Object.callback (C:\Projects\Deon\infrastructure\azureresources\node_modules\@pulumi\pulumi\runtime\invoke.js:139:33)
        at Object.onReceiveStatus (C:\Projects\Deon\infrastructure\azureresources\node_modules\@grpc\grpc-js\src\client.ts:338:26)
        at Object.onReceiveStatus (C:\Projects\Deon\infrastructure\azureresources\node_modules\@grpc\grpc-js\src\client-interceptors.ts:426:34)
        at Object.onReceiveStatus (C:\Projects\Deon\infrastructure\azureresources\node_modules\@grpc\grpc-js\src\client-interceptors.ts:389:48)
        at C:\Projects\Deon\infrastructure\azureresources\node_modules\@grpc\grpc-js\src\call-stream.ts:276:24
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Expected would for this to just work. There are valid scenarios for keeping the resourcegroup creation outside of Pulumi.

**Comment by ModernRonin** [comment]
changing the code to

```typescript
const resourceGroupName= cfg.require("ResourceGroup");
const resourceGroup= new resources.ResourceGroup(resourceGroupName);


// ...

const keys= pulumi.all([resourceGroup.name, cache.name])
                 .apply(([resourceGroupName, name])=>redis.listRedisKeys({resourceGroupName, name}))
```

seems to work as a work-around

**Comment by mikhailshilkov** [comment]
This is likely specific to the resource `cache.Redis`, or rather any resource with the name property called exactly "name".

A workaround is to include another property into `pulumi.all`:

```json
const keys= pulumi.all([resourceGroup.name, cache.name, cache.id])
```

**Comment by ModernRonin** [comment]
in azure that's a lot of resources...

**Comment by mikhailshilkov** [comment]
We may have to wait until https://github.com/pulumi/pulumi/issues/5758 ships which should reduce the need to call functions inside an `apply` altogether

**Comment by Cvaniak** [comment]
Similar situation existed for `azure_native.storage.list_storage_account_keys`.  
If you try to invoke it directly and ResourceGroup does not exist yet it frows an error:
```bash
Exception: invoke of azure-native:storage:listStorageAccountKeys failed: invocation of azure-native:storage:listStorageAccountKeys returned an error:
 request failed /subscriptions/xxx/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{accountName}/listKeys: autorest/azure:
 Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '{resourceGroupName}' could not be found."
```  
as solution for this problem you can use somthing like above:
```python
    connection_string = pulumi.Output.all(
        resource_group.name, storage_account.name
    ).apply(
        lambda x: azure_native.storage.list_storage_account_keys(
            resource_group_name=x[0], account_name=x[1]
        )
    )

```
there is not much about this error so I post this here so someone who will be struggling with this in the future will have more sources of help.

**Comment by mikhailshilkov** [comment]
A general solution to this class of problems is tracked in https://github.com/pulumi/pulumi/issues/9593, so I'll resolve this particular issue as a duplicate
