### ISSUE TITLE
Examples/simple fails during `pulumi preview` due to missing resource group

### ISSUE THREAD

**Issue by T-Vova** [pulumi/pulumi-azure-native#1043]
## Steps to reproduce
Running `pulumi preview` or `pulumi up` in the simple example leads to an unhanded exception as the resource group "Azure-Account-Cleanup" doesn't exist:

```
Diagnostics:
  pulumi:pulumi:Stack (simple-dev):
    error: Running program '/home/vova/pulumi-azure-native/examples/simple' failed with an unhandled exception:
    Error: invocation of azure-native:resources:getResourceGroup returned an error: request failed /subscriptions/e42a364a-2eaa-4d7d-9cd9-51d8b2ac497c/resourcegroups/Azure-Account-Cleanup: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'Azure-Account-Cleanup' could not be found."
        at Object.callback (/home/vova/pulumi-azure-native/sdk/nodejs/node_modules/@pulumi/pulumi/runtime/invoke.js:140:33)
        at Object.onReceiveStatus (/home/vova/pulumi-azure-native/sdk/nodejs/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/home/vova/pulumi-azure-native/sdk/nodejs/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/home/vova/pulumi-azure-native/sdk/nodejs/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /home/vova/pulumi-azure-native/sdk/nodejs/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
...
...
...
```

**Comment by mikhailshilkov** [comment]
The resource group does exist in our CI account, I suspect you are logged into a different subscription.

I realize it's not universally useful but I run this example as a smoke test for dev changes, and this particular call makes sure that invokes (functions) work.

**Comment by nesl247** [comment]
I think the point is that examples should work for anyone without any changes, not require any other resources to exist.

**Comment by viveklak** [comment]
> I think the point is that examples should work for anyone without any changes, not require any other resources to exist.

The examples in the provider repositories in some ways are a slight misnomer - they are often used as E2E/integration tests. Generally we recommend using the [pulumi/examples](https://github.com/pulumi/examples) repository for generally applicable examples. I understand this runs counter to what is in https://github.com/pulumi/pulumi-azure-native#running-an-example. I think we should just point to examples from https://github.com/pulumi/examples instead there.
