### ISSUE TITLE
Provider Crashes when creating a File Share

### ISSUE THREAD

**Issue by guidola** [pulumi/pulumi-azure-native#1192]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Creating a file share fails with 

```console
13:47:13  Diagnostics:
13:47:13    azure-native:storage:FileShare :
13:47:13      error: transport is closing
```

due to a previous stack crash on the provider:

```console
pulumi:pulumi:Stack :
13:47:13      panic: interface conversion: interface {} is map[string]interface {}, not string
13:47:13      goroutine 24 [running]:
13:47:13      github.com/pulumi/pulumi-azure-native/provider/pkg/provider.(*azureNativeProvider).prepareAzureRESTInputs(0xc0002d8300, 0xc0032e4870, 0x85, 0xc004553340, 0x4, 0x4, 0xc01246bad0, 0xc01009b2c0, 0x8, 0x1429570, ...)
13:47:13      	/home/runner/work/pulumi-azure-native/pulumi-azure-native/provider/pkg/provider/provider.go:1606 +0x88b
13:47:13      github.com/pulumi/pulumi-azure-native/provider/pkg/provider.(*azureNativeProvider).Invoke(0xc0002d8300, 0x1413588, 0xc01246b980, 0xc00c5612c0, 0xc0002d8300, 0x10dbd01, 0xc01245f080)
13:47:13      	/home/runner/work/pulumi-azure-native/pulumi-azure-native/provider/pkg/provider/provider.go:244 +0x5ea
13:47:13      github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1(0x1413588, 0xc01246b980, 0x11d5e80, 0xc00c5612c0, 0x11e18a0, 0x25689c0, 0x1413588, 0xc01246b980)
13:47:13      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.10.3-0.20210818190730-68b4cd756da5/proto/go/provider.pb.go:2501 +0x89
13:47:13      github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1413588, 0xc01246b590, 0x11d5e80, 0xc00c5612c0, 0xc010957580, 0xc01247c258, 0x0, 0x0, 0x13f92a0, 0xc00023e980)
13:47:13      	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
13:47:13      github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler(0x122f900, 0xc0002d8300, 0x1413588, 0xc01246b590, 0xc00c561260, 0xc0003e8de0, 0x1413588, 0xc01246b590, 0xc01247e240, 0x203)
13:47:13      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.10.3-0.20210818190730-68b4cd756da5/proto/go/provider.pb.go:2503 +0x150
13:47:13      google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002fe1c0, 0x141eb38, 0xc000001b00, 0xc00fb4b8c0, 0xc00dd77290, 0x2528060, 0x0, 0x0, 0x0)
13:47:13      	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
13:47:13      google.golang.org/grpc.(*Server).handleStream(0xc0002fe1c0, 0x141eb38, 0xc000001b00, 0xc00fb4b8c0, 0x0)
13:47:13      	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
13:47:13      google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00e1a2c20, 0xc0002fe1c0, 0x141eb38, 0xc000001b00, 0xc00fb4b8c0)
13:47:13      	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
13:47:13      created by google.golang.org/grpc.(*Server).serveStreams.func1
13:47:13      	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
```

### Steps to reproduce

1. Declare a File Share 

```typescript
const share= new FileShare(`${name}-share`, {
    accountName: storageAccountName,              // This name is a stack output
    resourceGroupName: resourceGroup.name,
    shareName: `${name}-share`,
    accessTier: "Hot",
})
```

2. deploy the stack
3.
4.

Expected: 

The stack gets created OK

Actual: 

The provider crashes.

**Comment by mikhailshilkov** [comment]
Hi @guidola thank you for reporting this and sorry for the trouble.

I tried the following simple repro code:

```ts
import * as resources from "@pulumi/azure-native/resources";
import * as storage from "@pulumi/azure-native/storage";
​
const resourceGroup = new resources.ResourceGroup("rg");

const name = "abc";

const storageAccount = new storage.StorageAccount("sa", {
    resourceGroupName: resourceGroup.name,
    sku: {
        name: storage.SkuName.Standard_LRS,
    },
    kind: storage.Kind.StorageV2,
});

const share= new storage.FileShare(`${name}-share`, {
    accountName: storageAccount.name,
    resourceGroupName: resourceGroup.name,
    shareName: `${name}-share`,
    accessTier: "Hot",
});
```

but `pulumi` up` worked just fine.

The stack trace shows the `Invoke` function which means you are calling some function like `getXyz` or `listXyz` - is that so? Could you share your full repro? Could you please also share the version of the provider?

**Comment by mikhailshilkov** [comment]
@guidola sorry for pinging you but I'd really love to reproduce and fix this panic. Any chance you still have a repro?
