### ISSUE TITLE
C# - PublicIPAddressSkuArgs results in GoLang error

### ISSUE THREAD

**Issue by snwbldsw** [pulumi/pulumi-azure-native#1515]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Whilst trying to add values to PublicIPAddressSkuArgs (in C#) I have the following error: 

```bash
panic: runtime error: comparing uncomparable type resource.PropertyMap
    goroutine 15 [running]:
    [github.com/pulumi/pulumi-azure-native/provider/pkg/provider.(*azureNativeProvider).Diff(0x14000472300](http://github.com/pulumi/pulumi-azure-native/provider/pkg/provider.(*azureNativeProvider).Diff(0x14000472300), {0x105b68ac8, 0x1401416a7b0}, 0x14000556230)
        /home/runner/work/pulumi-azure-native/pulumi-azure-native/provider/pkg/provider/provider.go:737 +0x9e8
    [github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0x105b68ac8](http://github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1(%7B0x105b68ac8), 0x1401416a7b0}, {0x105ad8900, 0x14000556230})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.23.2/proto/go/provider.pb.go:2611 +0x7c
    [github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x105b68ac8](http://github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(%7B0x105b68ac8), 0x1401416a480}, {0x105ad8900, 0x14000556230}, 0x14012535f60, 0x1401415c858)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3bc
    [github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0x105b19c00](http://github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler(%7B0x105b19c00), 0x14000472300}, {0x105b68ac8, 0x1401416a480}, 0x1400e3ea120, 0x14000643f00)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.23.2/proto/go/provider.pb.go:2613 +0x150
    [google.golang.org/grpc.(*Server).processUnaryRPC(0x140004f2000](http://google.golang.org/grpc.(*Server).processUnaryRPC(0x140004f2000), {0x105b7a0e8, 0x1400017ec00}, 0x1401416c000, 0x140140f8b70, 0x106ddee28, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0xc38
    [google.golang.org/grpc.(*Server).handleStream(0x140004f2000](http://google.golang.org/grpc.(*Server).handleStream(0x140004f2000), {0x105b7a0e8, 0x1400017ec00}, 0x1401416c000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xa34
    [google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400c6e4020](http://google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400c6e4020), 0x140004f2000, {0x105b7a0e8, 0x1400017ec00}, 0x1401416c000)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0x94
    created by [google.golang.org/grpc.(*Server).serveStreams.func1](http://google.golang.org/grpc.(*Server).serveStreams.func1)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1f0
```

Below is the full code for the Public IP I'm trying to add: 

```csharp
         var publicIPAddress = new AzureNative.Network.PublicIPAddress("publicIPAddress", new AzureNative.Network.PublicIPAddressArgs
         {
             Location = "uksouth",
             Tags = { { "project", "ProjectName"}, {"deployment", "Pulumi"} },
             PublicIpAddressName = $"{Deployment.Instance.StackName}-pip",
             ResourceGroupName = $"{Deployment.Instance.StackName}-rg",
             PublicIPAddressVersion = "IPv4",
             PublicIPAllocationMethod = "Static",
             IdleTimeoutInMinutes = 4,
             Sku = new AzureNative.Network.Inputs.PublicIPAddressSkuArgs
             {
                 Name = "Standard",
                 Tier = "Regional"
             }
         });
```

If I remove the sku = lines it works fine, but then causes later issues as I need to use WAF v2 for the application gateway code, which means I need to set specific values for the Name/Tier in order for the pip to comply with the requirements

### Steps to reproduce

1. Try to use the above code in a C# build and it fails
2. Remove Sku = section and it works

Expected:  Creation of PIP with proper values
Actual:  GoLang panic error

**Comment by danielrbradley** [comment]
Confirmed this applies to all languages. Equivelent example in Typescript:

```typescript
const resourceGroup = new resources.ResourceGroup("resource-group");

new network.PublicIPAddress("ip", {
  resourceGroupName: resourceGroup.name,
  publicIPAllocationMethod: "Static",
  // Creating then adding the below lines causes a provider panic
  //   sku: {
  //     name: "Standard",
  //     tier: "Regional",
  //   },
});
```

If the SKU is defined at the point of initial create it does not fail, and the SKU can be removed, however, if the SKU is not present but is then added the preview will fail with the panic above.

@snwbldsw one workaround here is to remove your existing PIP then create as a new resource including the SKU (I think changing the SKU causes a replace anyway behind the scenes).
