### ISSUE TITLE
OperationalInsights Workspace expects lastSkuUpdate

### ISSUE THREAD

**Issue by FlomoN** [pulumi/pulumi-azure-native#1962]
### What happened?

Trying to create a log Analytics Workspace in Java fails.

### Steps to reproduce

```java
// Log Analytics Workspace
            var logAnalytics = new Workspace(PREFIX + "law",
                    WorkspaceArgs.builder()
                            .location(LOCATION)
                            .workspaceName(PREFIX + "law")
                            .resourceGroupName(PREFIX + "rg")
                            .build());
```

### Expected Behavior

To create a log analytics workspace without issues

### Actual Behavior

```
Diagnostics:
  pulumi:pulumi:Stack (dmp-dev):
    Sept. 11, 2022 8:13:40 AM com.pulumi.deployment.internal.DeploymentImpl$DefaultEngineLogger errorAsync
    SCHWERWIEGEND: Running program [PID: 21576](unknown) failed with an unhandled exception:
    java.lang.UnsupportedOperationException: Convert [com.pulumi.azurenative.operationalinsights.Workspace.sku]: Error converting 'com.google.common.collect.SingletonImmutableBiMap' to 'TypeShape{type=class com.pulumi.azurenative.operationalinsights.outputs.WorkspaceSkuResponse, parameters=[]}'. Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:119)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:86)
        at com.pulumi.core.internal.OutputCompletionSource.setValue(OutputCompletionSource.java:95)
        at com.pulumi.deployment.internal.DeploymentImpl$ReadOrRegisterResourceInternal.lambda$completeResourceAsync$0(DeploymentImpl.java:1193)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
    Caused by: java.lang.IllegalStateException: Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:450)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at com.pulumi.serialization.internal.Converter.tryConvertObjectInner(Converter.java:409)
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:115)
        ... 10 more
    Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:441)
        ... 13 more
    Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at com.pulumi.azurenative.operationalinsights.outputs.WorkspaceSkuResponse$Builder.lastSkuUpdate(WorkspaceSkuResponse.java:81)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 15 more

    error: Running program [PID: 21576](unknown) failed with an unhandled exception:
    java.lang.UnsupportedOperationException: Convert [com.pulumi.azurenative.operationalinsights.Workspace.sku]: Error converting 'com.google.common.collect.SingletonImmutableBiMap' to 'TypeShape{type=class com.pulumi.azurenative.operationalinsights.outputs.WorkspaceSkuResponse, parameters=[]}'. Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:119)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:86)
        at com.pulumi.core.internal.OutputCompletionSource.setValue(OutputCompletionSource.java:95)
        at com.pulumi.deployment.internal.DeploymentImpl$ReadOrRegisterResourceInternal.lambda$completeResourceAsync$0(DeploymentImpl.java:1193)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
    Caused by: java.lang.IllegalStateException: Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:450)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at com.pulumi.serialization.internal.Converter.tryConvertObjectInner(Converter.java:409)
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:115)
        ... 10 more
    Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:441)
        ... 13 more
    Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at com.pulumi.azurenative.operationalinsights.outputs.WorkspaceSkuResponse$Builder.lastSkuUpdate(WorkspaceSkuResponse.java:81)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 15 more
    error: an unhandled error occurred: 'E:\Flo\vscode\dmp\infra\mvnw.cmd E:\Flo\vscode\dmp\infra\mvnw.cmd -Dorg.slf4j.simpleLogger.defaultLogLevel=warn --no-transfer-progress compile exec:java' exited with non-zero exit code: 1
```

### Output of `pulumi about`

CLI
Version      3.39.3  
Go Version   go1.19.1
Go Compiler  gc      

Plugins
NAME          VERSION
azure-native  1.76.0
java          unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19043 Build 19043
Arch     x86_64

This project is written in java: executable='C:\Program Files\Common Files\Oracle\Java\javapath\java.exe' version='java 18.0.1.1 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)' java='C:\Program Files\Common Files\Oracle\Java\javapath\java.exe' javac='18.0.1.1'

Current Stack: dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::dmp::pulumi:pulumi:Stack::dmp-dev
pulumi:providers:azure-native               urn:pulumi:dev::dmp::pulumi:providers:azure-native::default_1_76_0
azure-native:operationalinsights:Workspace  urn:pulumi:dev::dmp::azure-native:operationalinsights:Workspace::dev-dmp-law

Found no pending operations associated with dev

Backend
Name           DESKTOP-AE4886R
URL            azblob://dmp-state
User           DESKTOP-AE4886R\flogi
Organizations

No dependencies found

Pulumi locates its logs in C:\Users\flogi\AppData\Local\Temp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by FlomoN** [comment]
This already seems to break in 1.73.0 (still works in 1.72.0)

**Comment by jkisk** [comment]
Thank you for filing, we will look into this!
