### ISSUE TITLE
Creating Blob with a StringAsset throws Unmarshaling Exception

### ISSUE THREAD

**Issue by jpmckearin** [pulumi/pulumi-azure-native#642]
When trying to create a storage blob using a `StringAsset` and passing in XML, an error is thrown. I was able to get around this for now by using a `FileAsset` instead.

## Expected behavior
I expected the Blob to be created with the string passed into `StringAsset` to be in the contents of the blob.

## Current behavior
The error is thrown: `Error: Invalid asset encountered when unmarshaling resource property`

## Steps to reproduce

Live Preview: https://app.pulumi.com/ContessaHealth/unicode/dev/previews/3acd6512-2146-4071-879c-c941b18f66cc
1. Create a BlobContainer resource
2. Attempt to create a Blob resource using a `new StringAsset('<?xml version="1.0" encoding="utf-8"?><repository></repository>')` as the `source`

## Context (Environment)

```typescript
const dataProtectionBlob = new Blob(
  'dataProtectionBlob',
  {
    blobName: 'data-protection-key.xml',
    accountName: currentStorageAccount.name,
    containerName: dataProtectionContainer.name,
    type: 'Block',
    contentType: 'application/xml',
    source: new StringAsset('<?xml version="1.0" encoding="utf-8"?><repository></repository>'),
    resourceGroupName
  },
  { ignoreChanges: ['source'] }
)
```

**Comment by mikhailshilkov** [comment]
Stack trace (from Slack):

```
    Error: Invalid asset encountered when unmarshaling resource property
        at deserializeProperty (/Users/blah/source/blah/unicode/infra/node_modules/@pulumi/azure-native/node_modules/@pulumi/pulumi/runtime/rpc.js:437:31)
        at deserializeProperty (/Users/blah/source/blah/unicode/infra/node_modules/@pulumi/azure-native/node_modules/@pulumi/pulumi/runtime/rpc.js:506:23)
        at deserializeProperty (/Users/blah/source/blah/unicode/infra/node_modules/@pulumi/azure-native/node_modules/@pulumi/pulumi/runtime/rpc.js:463:32)
        at Object.deserializeProperties (/Users/blah/source/blah/unicode/infra/node_modules/@pulumi/azure-native/node_modules/@pulumi/pulumi/runtime/rpc.js:126:24)
        at /Users/blah/source/blah/unicode/infra/node_modules/@pulumi/azure-native/node_modules/@pulumi/pulumi/runtime/resource.js:524:43
        at Generator.next (<anonymous>)
        at /Users/blah/source/blah/unicode/infra/node_modules/@pulumi/azure-native/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/blah/source/blah/unicode/infra/node_modules/@pulumi/azure-native/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
        at resolveOutputs (/Users/blah/source/blah/unicode/infra/node_modules/@pulumi/azure-native/node_modules/@pulumi/pulumi/runtime/resource.js:519:12)
    error: update failed
```

**Comment by boillodmanuel** [comment]
I encountered a similar issue I described here: https://github.com/pulumi/pulumi/issues/6691

**Comment by furier** [comment]
I am having the same issue but with the `FileAsset` type.

```ts
pulumi:pulumi:Stack (Connected-dev):
    error: Running program 'C:\dev\Connected\infrastructure/' failed with an unhandled exception:
    <ref *1> Error: Invalid asset encountered when unmarshaling resource property
        at deserializeProperty (C:\dev\Connected\infrastructure\node_modules\@pulumi\runtime\rpc.ts:578:27)
        at deserializeProperty (C:\dev\Connected\infrastructure\node_modules\@pulumi\runtime\rpc.ts:671:23)
        at deserializeProperty (C:\dev\Connected\infrastructure\node_modules\@pulumi\runtime\rpc.ts:605:28)
        at Object.deserializeProperties (C:\dev\Connected\infrastructure\node_modules\@pulumi\runtime\rpc.ts:181:24)
        at C:\dev\Connected\infrastructure\node_modules\@pulumi\runtime\resource.ts:798:33
        at Generator.next (<anonymous>)
        at C:\dev\Connected\infrastructure\node_modules\@pulumi\pulumi\runtime\resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (C:\dev\Connected\infrastructure\node_modules\@pulumi\pulumi\runtime\resource.js:17:12)
        at resolveOutputs (C:\dev\Connected\infrastructure\node_modules\@pulumi\pulumi\runtime\resource.js:676:12) {
      promise: Promise { <rejected> [Circular *1] }
    }
```

Here is the code that produce the error... It works most of the time but every now and then we need to comment out the `FileAsset`, run `pulumi up` and then put it in again to make it work. Suspecting the state gets screwed up sometimes...
```ts
const scriptFile = new pulumi.asset.FileAsset(scriptPath);
    
const scriptBlob = new azurenative.storage.Blob(scriptName, {
      accountName: this.dataLake.resource.name,
      containerName: 'scripts',
      resourceGroupName: this.args.rg.resource.name,
      blobName: scriptName,
      type: 'Block',
      contentType: 'text/plain',
      source: scriptFile,
});
```

**Comment by furier** [comment]
This issue is a big problem for us as we need to refresh state after each deployment when swapping staging and production environments after a pulumi deployment. Because when deploying we are refreshing the staging slot's app settings and updating it accordingly, after it has been swapped to production the old settings are now in the staging slot and need to be refreshed for pulumi to know what to update for next slot swap.

**Comment by Tungsten78** [comment]
We too have encountered this immediately after a `pulumi refresh` - which is more consistent with #6691.

> This issue is a big problem for us as we need to refresh state after each deployment when swapping staging and production environments after a pulumi deployment. Because when deploying we are refreshing the staging slot's app settings and updating it accordingly, after it has been swapped to production the old settings are now in the staging slot and need to be refreshed for pulumi to know what to update for next slot swap.

**Comment by justinvp** [comment]
For the refresh issue, I suspect the fix for #14078 may have addressed this (shipped in v3.87.0 of the Pulumi CLI), and if not, then the proposed fix for https://github.com/pulumi/pulumi/issues/17131#issuecomment-2336933020 likely will.
