### ISSUE TITLE
Can't use the 'Any' Operator in Azure Frondoor Rules Engine 

### ISSUE THREAD

**Issue by jfawcett2000** [pulumi/pulumi-azure-native#646]
When creating a RulesEngine for Azure Frontdoor, I am not able to provide it with a rule condition based on the **Any** operator. 

```
new AzureNative.Network.Inputs.RulesEngineRuleArgs
{
    MatchConditions = new List<AzureNative.Network.Inputs.RulesEngineMatchConditionArgs>
    {
        new AzureNative.Network.Inputs.RulesEngineMatchConditionArgs
        {
            RulesEngineMatchVariable = RulesEngineMatchVariables.RequestHeader,
            Selector = RoutingHeaders.RegionHeader,
            RulesEngineOperator = RulesEngineOperators.Any,
            //RulesEngineMatchValue = "",
            NegateCondition = true
        },
```

## Expected behavior
I should not need to supply the `RulesEngineMatchValue` commented out above.

## Current behavior
If I don't supply a value, I get

```
 System.ArgumentNullException: [Input] Pulumi.AzureNative.Network.Inputs.RulesEngineMatchConditionArgs._rulesEngineMatchValue is required but was not given a value (Parameter '_rulesEngineMatchValue')
       at Pulumi.InputArgs.ToDictionaryAsync()
       at Pulumi.Serialization.Serializer.SerializeInputArgsAsync(String ctx, InputArgs args, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeListAsync(String ctx, IList list, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeDictionaryAsync(String ctx, IDictionary dictionary, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeInputArgsAsync(String ctx, InputArgs args, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeListAsync(String ctx, IList list, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```
If I supply a value, I get

```
Rules Engines validation failed. More information: Match value(s) must not be provided for Operator 'Any'.
```

It would appear it's not possible (currently) to use the **Any** condition.

**Comment by jfawcett2000** [comment]
The equivalent rule in the ARM template that I'm trying to achieve is:

```
                        "matchConditions": [
                            {
                                "rulesEngineMatchValue": [],
                                "rulesEngineMatchVariable": "RequestHeader",
                                "rulesEngineOperator": "Any",
                                "transforms": [],
                                "negateCondition": true,
                                "selector": "myheader"
                            },
```

**Comment by jfawcett2000** [comment]
> The property is marked as required in the specs [here](https://github.com/Azure/azure-rest-api-specs/blob/d71dcdc7d0d9675d31b1b5e5acea0daeb52f90db/specification/frontdoor/resource-manager/Microsoft.Network/stable/2020-05-01/frontdoor.json#L1914).
> 
> > Rules Engines validation failed. More information: Match value(s) must not be provided for Operator 'Any'.
> 
> Which value are you providing in this case? You code shows `""` which seems wrong - why provide an empty string? I'd expect it to be an empty array `RulesEngineMatchValue = {},`.

I had tried empty strings, empty arrays, nothing works. As I say, it expects a value, but Azure doesn't expect one when you use **Any**.

**Comment by jfawcett2000** [comment]
This may be a problem in the Azure API. There's a similar problem reported in the powershell repo for CDNs:
https://github.com/Azure/azure-powershell/issues/13989

**Comment by mikhailshilkov** [comment]
May I ask you to set the parameter to an empty array, then run the operation with all debug flags `pulumi up -v=9 --debug --logtostderr --logflow >> log.txt`, find the raw HTTP payload that we are sending, and paste it here? If it looks legit, we should report to Azure.

**Comment by jfawcett2000** [comment]
This seems to have worked!

```
RulesEngineMatchValue = new List<string>(),
```

When I used this:

```
RulesEngineMatchValue = { }
```

I still get:

```
 Pulumi.AzureNative.Network.Inputs.RulesEngineMatchConditionArgs._rulesEngineMatchValue is required but was not given a value
```

I'll leave it up to you if you want to close this off. Might need some docs updated with this example though.

Full rule:

```
new AzureNative.Network.Inputs.RulesEngineRuleArgs
{
    MatchConditions = new List<AzureNative.Network.Inputs.RulesEngineMatchConditionArgs>
    {
        // e.g. if a particular request header isn't present
        new AzureNative.Network.Inputs.RulesEngineMatchConditionArgs
        {
            RulesEngineMatchVariable = RulesEngineMatchVariables.RequestHeader,
            Selector = RoutingHeaders.RegionHeader,
            RulesEngineOperator = RulesEngineOperators.Any,
            RulesEngineMatchValue = new List<string>(),
            NegateCondition = true
        },
```

**Comment by jfawcett2000** [comment]
It definitely omits the match value from the payload, if that helps.

```
"matchConditions":[
    pulumi:pulumi:Stack edge-devedge running           {
    pulumi:pulumi:Stack edge-devedge running             "rulesEngineMatchValue":[
    pulumi:pulumi:Stack edge-devedge running             ],"rulesEngineMatchVariable":"RequestHeader","rulesEngineOperator":"Any","transforms":[
    pulumi:pulumi:Stack edge-devedge running             ],"negateCondition":true,"selector":"**redacted**"
    pulumi:pulumi:Stack edge-devedge running           }
```

**Comment by mikhailshilkov** [comment]
Thanks for following up on this. I think I understand why this happens... `{ }` is actually a no-op, it does nothing in C# (calls the `.Add` method 0 times). `new List<string>()` does actually initialize the list to be an empty list.

That's a bit counter-intuitive (it got me too). However, I don't see any obvious action points so I'll go ahead and close the issue for now.
