### ISSUE TITLE
Cannot define a EmptyDir volume in a ContainerGroup

### ISSUE THREAD

**Issue by HendrikGerken** [pulumi/pulumi-azure-native#648]
I'm trying to create an [EmptyDir volume](https://docs.microsoft.com/en-gb/azure/container-instances/container-instances-volume-emptydir) in Azure Container Instances / Group. This [ContainerGroup documentation](https://www.pulumi.com/docs/reference/pkg/azure-native/containerinstance/containergroup/#containergroupscreateorupdate) says I should do it like this:
```csharp
var containerGroup = new AzureNative.ContainerInstance.ContainerGroup("containerGroup", new AzureNative.ContainerInstance.ContainerGroupArgs
{
   // [...]
    Volumes = 
    {
        // [...]
        new AzureNative.ContainerInstance.Inputs.VolumeArgs
        {
            EmptyDir = ,
            Name = "volume2",
        },
        // [...]
    },
};
```
First of all, this cannot be done this way, as the compiler does not like an assignment without a value. So i tried different values hoping that one will somehow work, but until now I couldn't figure it out.

If I set `EmptyDir` to `null`, the Azure resource cannot be created, as one the properties `AzureFile`, `EmptyDir`, `Secret `or `GitRepo` must be specified. Here creating or updating the Azure Container Instance Resource fails on Azure site because of the invalid configuration.

If I set `EmptyDir` to something else, like `new object()`, `0`, `string.Empty`, or to an anonymous type `{ }` an exception like this is thrown during the planning:

```text
    System.InvalidOperationException: System.Object is not a supported argument type.
        resource:containerGroup[azure-native:containerinstance:ContainerGroup].volumes.id[4].emptyDir.id.id
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeDictionaryAsync(String ctx, IDictionary dictionary, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeInputArgsAsync(String ctx, InputArgs args, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeListAsync(String ctx, IList list, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args, Boolean keepResources)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()

```

## Expected behavior

- Documentation with working code
- A way to specify `EmptyDir` volumes in a Container Group

## Current behavior

- Documentation gives invalid / not compilable code
- Setting `EmptyDir` to something not `null` causes an `InvalidOperationException` during the planning.

## Steps to reproduce
Create a `ContainerGroup` containing a `EmptyDir` volume.

## Context (Environment)
I tried to set up a Container Group with Azure Container Instances that contain multiple container which should share "EmptyDir" volumes for configuration files and custom container entrypoint scripts. These files are planned to be provided by an InitContainer, which mounts the EmptyDir volume too.

Versions:
- Pulumi: 2.21.2 & 2.22.0
- AzureNative: 0.7.1

**Comment by mikhailshilkov** [comment]
Sorry for the hurdle. Could you please try `new Dictionary<string, object>()`?

**Comment by HendrikGerken** [comment]
I can confirm now that it works with:
```csharp
new VolumeArgs
{
    Name = "initvol",
    EmptyDir = new Dictionary<string, object>(),
},
```

Thanks for your quick help.
