### ISSUE TITLE
Issue defining the correct definitions on ApiSchema

### ISSUE THREAD

**Issue by MohadKamil** [pulumi/pulumi-azure-native#828]
This is a follow up on the same question opened on stackoverflow [here](https://stackoverflow.com/questions/67365235/definitions-type-for-pulumi-api-management-api-schema-resource?noredirect=1#comment119116431_67365235)

Definitions property of ApiSchema requires an inline dictionary for the API schema types, the only dictionary type that passes pulumi valdidation is Dictionary<string,string>, this result in the json payload sent to azure API having escape characters, which I suspect are the reason for the error: "The Async Operation failed"

Json Request payload that pulumi sends

```json
{"properties":{"contentType":"application/vnd.oai.openapi.components+json","document":{"definitions":{"apiResponse":"{\"Title\":\"apiResponse\",\"Type\":\"object\"}"}}}}
``` 
## Expected behavior

allow <string,object> dictionary type for definition property

## Current behavior
An InvalidOperationException is thrown

```
Running program 'C:\Users\mkami\source\repos\AzAPIMExporter\PulumiExporter\bin\Debug\netcoreapp3.1\PulumiExporter.dll' failed with an unhandled exception:
    System.InvalidOperationException: System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.OpenApi.Models.OpenApiSchema, Microsoft.OpenApi, Version=1.2.3.0, Culture=neutral, PublicKeyToken=3f5743946376f042]] is not a supported argument type.
        resource:schema[azure-native:apimanagement:ApiSchema].definitions.id.ApiResponse
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeDictionaryAsync(String ctx, IDictionary dictionary, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, Boolean remote, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.Logger.TryGetResourceUrnAsync(Resource resource)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

## Steps to reproduce

The snippets of code as follows
```csharp
 var schemas = new Dictionary<string, object>
            {
                {
                    "apiResponse", new
                    {
                        Title = "apiResponse",
                        Type = "object",

                    }
                }
            };

           //JsonConvert.SerializeObject from Json.NET
            var jsonSchema = schemas
                .ToDictionary(p => p.Key,
                    p => JsonConvert.SerializeObject(p.Value));
            
            var apiSchema = new ApiSchema("schema", new ApiSchemaArgs
            {
                ResourceGroupName = "rg",
                ServiceName = "apimservice",
                ApiId = "api",
                ContentType = "application/vnd.oai.openapi.components+json",
                SchemaId = "apischema",
                Definitions = jsonSchema
            });
```
## Context (Environment)
For the context, I'm trying to automate importing of APIs from and openapi document to an API in Azure API management, including operations, Request/Response payloads and schemas

**Comment by MohadKamil** [comment]
The serialization accepts JsonElement from the System.Text.Json so changing the definition to IDictionary<string,JsonElement> worked for me

**Comment by mikhailshilkov** [comment]
@MohadKamil Apologies for the slow response here. I'm glad to see you figured it out.

Should I close the issue now? Alternatively, do you want to change it to a proposal for an enhancement to improve our API?
